#===================
# TEST ENV
#===================

version: '3.8'

services:
  test_nginx:
    build: 
      context: ./client
      dockerfile: Dockerfile
    container_name: test_nginx_container
    expose:
      - 80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend-http.rule=HOST(`www.${TEST_DOMAIN}`,`${TEST_DOMAIN}`)"
      - "traefik.http.routers.frontend-http.tls=true" # HTTPS
      - "traefik.http.routers.frontend-http.tls.certresolver=letsencrypt"
      
  test_api:
    build: ./server/project
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    container_name: test_api_container
    volumes:
      - ./server/project:/usr/src/app # for automatic reloading
    expose:
      - 8000
    env_file:
      - ./server/.env.test
    depends_on:
      - postgres_db
      - mongo_db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.testapi.rule=Host(`${TEST_API_DOMAIN}`)"
      - "traefik.http.routers.testapi.tls=true" # HTTPS
      - "traefik.http.routers.testapi.tls.certresolver=letsencrypt"

  postgres_db:
    build:
      context: ./server/project/db
      dockerfile: Dockerfile
    container_name: postgres_db
    volumes:
      - postgres_data_test:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=flower_letter
      - POSTGRES_PASSWORD=flower_letter

  mongo_db:
    image: mongo:5.0.4
    container_name: mongo_db
    expose:
      - 27017
    volumes:
      - mongo_data_test:/var/lib/mongodb/data/
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=root
      - MONGODB_INITDB_ROOT_PASSWORD=password123

  test_ml:
    build:
      context: ./ml/model-api
      dockerfile: Dockerfile.comb
    # command: uvicorn app.main:app --host 0.0.0.0 --reload
    # volumes:
    #   - ./ml/model-api:/app # for auto reload
    container_name: test_ml_container
    expose:
      - 80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mlapi.rule=Host(`${TEST_ML_DOMAIN}`)"
      - "traefik.http.routers.mlapi.tls=true" # HTTPS
      - "traefik.http.routers.mlapi.tls.certresolver=letsencrypt"

volumes:
  postgres_data_test:
  mongo_data_test:
  traefik-public-certificates:

