version: '3.8'

services:

  postgres_db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    # expose:
    #   - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=flower_letter
      - POSTGRES_PASSWORD=flower_letter
      - POSTGRES_DB=flower_letter
  mongo_db:
    image: mongo:5.0.4
    ports: 
      - 27017:27017
    volumes:
      - mongo_data:/var/lib/mongodb/data/
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=root
      - MONGODB_INITDB_ROOT_PASSWORD=password123

volumes:
  postgres_data:
  mongo_data: