version: '3.8'

services:
  web:
    build: ./project
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./project:/usr/src/app # for automatic reloading of container after code change
    expose:
      - 8000
    env_file:
      - .env
    depends_on:
      - postgres_db
      - mongo_db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fastapi.rule=Host(`${DOMAIN}`)"

  postgres_db:
    build:
      context: ./project/db
      dockerfile: Dockerfile
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    # ports:
    #   - 5432:5432
    environment:
      - POSTGRES_USER=flower_letter
      - POSTGRES_PASSWORD=flower_letter

  mongo_db:
    image: mongo:5.0.4
    # ports: 
    #   - 27017:27017
    expose:
      - 27017
    volumes:
      - mongo_data:/var/lib/mongodb/data/
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=root
      - MONGODB_INITDB_ROOT_PASSWORD=password123
  
  traefik:
    image: traefik:v2.2
    ports:
      - 8008:80 # local 8008 to make requests
      - 8081:8080 # dashboard 8081
    volumes:
      - "./traefik.dev.toml:/etc/traefik/traefik.toml"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

volumes:
  postgres_data:
  mongo_data: