version: '3.8'

services:
  web:
    build: 
      context: ./project
      dockerfile: Dockerfile.prod
    ports:
      - 8009:80
    env_file:
      - .env.prod
    depends_on:
      - postgres_db
      - mongo_db

  postgres_db:
    build:
      context: ./project/db
      dockerfile: Dockerfile
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    # ports:
    #   - 5432:5432
    environment:
      - POSTGRES_USER=flower_letter
      - POSTGRES_PASSWORD=flower_letter

  mongo_db:
    image: mongo:5.0.4
    # ports: 
    #   - 27017:27017
    expose:
      - 27017
    volumes:
      - mongo_data:/var/lib/mongodb/data/
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=root
      - MONGODB_INITDB_ROOT_PASSWORD=password123

volumes:
  postgres_data:
  mongo_data: