version: '3.8'

services:
  mlweb:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --reload
    volumes:
      - .:/app # for auto reload
    ports:
      - 8008:8000