version: '3.8'

services:
  mlweb:
    build:
      context: .
      dockerfile: Dockerfile.test
    command: uvicorn app.main:app --host 0.0.0.0
    volumes:
      - .:/app # for auto reload
    ports:
      - 8008:8000