# Docker compose for local development

version: '3.8'

services:
  web_office:
    build:
      context: ./project
      dockerfile: Dockerfile
    volumes:
      - ./project:/app # for automatic reloading
    expose:
      - 5000
    ports:
      - 5000:5000
    env_file:
      - .env.dev
    networks:
      - yulie-net

networks:
  yulie-net:
    driver: bridge

